### ISSUE TITLE
NoClassDefFoundError for org.eclipse.m2m.scm.ScmUrl when running groovy script

### ISSUE THREAD

**Issue by marioja** [eclipse-ease-addons/groovy#3]
When running this groovy script with EASE

    import org.eclipse.m2e.scm.ScmUrl

    org.eclipse.m2e.scm.ScmUrl scmUrls= new org.eclipse.m2e.scm.ScmUrl[1]{new org.eclipse.m2e.scm.ScmUrl("scm:" + "svn" + ":" + "http://sdevbtvap2235.tst.dce-   eir.net/eci/cbsapom/ics-parent/trunk")}

I get this error

    java.lang.NoClassDefFoundError: [Lorg/eclipse/m2e/scm/ScmUrl;
    	at scm-import.run(scm-import.groovy:3)
    	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:521)
    	at org.eclipse.ease.lang.groovy.interpreter.GroovyScriptEngine.execute(GroovyScriptEngine.java:72)
    	at org.eclipse.ease.AbstractScriptEngine.inject(AbstractScriptEngine.java:245)
    	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:309)
    	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
    Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.scm.ScmUrl
    	at java.net.URLClassLoader.findClass(Unknown Source)
    	at java.lang.ClassLoader.loadClass(Unknown Source)
    	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:773)
    	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:528)
    	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:883)
    	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:871)
    	... 6 more

**Comment by marioja** [comment]
I guess the problem is that I do not have access to the org.eclipse.m2e.scm plugin classes.  Normally in a plugin project you add it as a dependency but I do not know how to do this with groovy.

**Comment by Pontesegger** [comment]
Ease is using buddy classloading which should grant you access to all available classes from other plugins. Are you sure the plugin you require is started? If not, its classes are not accessible

**Comment by marioja** [comment]
The plugin is definitely started as I can use it within Eclipse.  Do you have any idea as to when someone is going to have a look at this issue?

**Comment by Pontesegger** [comment]
reported upstream: https://bugs.eclipse.org/bugs/show_bug.cgi?id=560577

**Comment by Pontesegger** [comment]
fixed upstream
